# Application configuration (external, not bundled in JAR)
smartnaming:
  used-model: local-qwen
  max-retries: 3
  models:
    local-qwen:
      url: http://localhost:1234/v1
      model: qwen3.5_4B
    open-ai:
      url: https://api.openai.com/v1
      model: gpt-4o
      auth:
        api-token: ${OPENAI_API_KEY:}
